#' This function takes in sample ID, participant ID and somalier.pairs file generated by somalier and creates a final tsv final consisting of 
#' summary statistics of relatedness, number of related samples, heterozygostiy mean per sample, relatedness above two thresholds (0.8 and 0.6) 
#' written by William Mischler 
#' updated by Yohana Kefella
if (!require('tidyverse')) install.packages('tidyverse'); library('tidyverse')
if (!require('dplyr')) install.packages('dplyr'); library('dplyr')

somalier_stats <- function(somalier_file, sample_id, participant_id) {
  #read in somalier file
  somalier.pairs <- read.delim(somalier_file, header=TRUE, stringsAsFactors=FALSE)
  
  
  #match participant ids to id names
  somalier.pairs$sample_a_id <- participant_id[match(somalier.pairs$X.sample_a,sample_id)]
  somalier.pairs$sample_b_id <- participant_id[match(somalier.pairs$sample_b,sample_id)]
  
  
  #initialize matrix of proper size
  par_out<-matrix(ncol= 15, nrow = length(sample_id))
  
  
  #first computes all samples for relatedness to samples not labeled as same participant
  #then works on the samples that are supposed to be related (checks to see if any pairs have same participant id and then breaks inner for loop)
  for (i in 1:nrow(par_out)) {
    for (j in 1:nrow(somalier.pairs)) {
      if (somalier.pairs$sample_a_id[j] == participant_id[i] & somalier.pairs$sample_b_id[j] != participant_id[i] |
          somalier.pairs$sample_a_id[j] != participant_id[i] & somalier.pairs$sample_b_id[j] == participant_id[i]){
        ix <- somalier.pairs$sample_a_id == participant_id[i] & somalier.pairs$sample_b_id != participant_id[i] |
          somalier.pairs$sample_a_id != participant_id[i] & somalier.pairs$sample_b_id == participant_id[i]
        
        su <- summary(somalier.pairs$relatedness[ix])
        par_out[i,5:8]<- round(su[c(4,3,6,1)], 4)
        temp<-somalier.pairs[ix,]
      }
      if (somalier.pairs$sample_a_id[j] == participant_id[i] & somalier.pairs$sample_b_id[j] == participant_id[i]) {
        ix1 <- somalier.pairs$sample_a_id == participant_id[i] & somalier.pairs$sample_b_id == participant_id[i]
        su_ <- summary(somalier.pairs$relatedness[ix1])
        tmp <- somalier.pairs
        tmp <- tmp %>% dplyr::mutate(sample_value_rel = paste("(",X.sample_a, sample_b, relatedness,")", sep = " "))
        tmp$heterozygosity_rate <- round(tmp$hets_a/(tmp$hets_a + tmp$hom_alts_a), 3)
        su_het <- summary(tmp$heterozygosity_rate[ix1])
        par_out[i,1:4]<- round(su_[c(4,3,6,1)], 4)
        par_out[i,9] <- round(su_het[4], 4)
        par_out[i,10:11]<-c(length(unique(c(tmp$sample_b[ix1], tmp$X.sample_a[ix1]))), paste(c(tmp$sample_value_rel[ix1]), collapse = ","))
        mj = which(ix1 == T)[1]
        #filter relatedness greater than 0.8 threshold 
        if (tmp$relatedness[mj]>0.8){
          x <- tmp %>% dplyr::filter(relatedness > 0.8 & X.sample_a == tmp$X.sample_a[mj]) %>% dplyr::select(sample_b, relatedness)
          par_out[i, 12]<- paste(c(x[,1]), collapse = ", ")
          par_out[i,13] <- paste0(x[,2], collapse=", ")
        }
        #filter relatedness greater than 0.6 threshold 
        if (tmp$relatedness[mj]>0.6){
          x <- tmp %>% dplyr::filter(relatedness > 0.6 & X.sample_a == tmp$X.sample_a[mj]) %>% dplyr::select(sample_b, relatedness)
          par_out[i, 14]<- paste(c(x[,1]), collapse = ", ")
          par_out[i,15] <- paste0(x[,2], collapse=", ")
        }
        break
      }
    }
  }
  
  rownames(par_out)<-sample_id
  colnames(par_out)<-c("somalier_relatedness_mean", "somalier_relatedness_median", "somalier_relatedness_max", "somalier_relatedness_min", "somalier_other_relatedness_mean", 
                       "somalier_other_relatedness_median", "somalier_other_relatedness_max", "somalier_other_relatedness_min", "somalier_heterozygosity_mean", "somalier_relatedness_num_samples", 
                       "matching_relatedness_with_sample_byAnnotation", "matching_relatedness_with_samples_byThreshold (> 0.8%)", "relatedness_value_with_samples_byThreshold (> 0.8%)",
                       "matching_relatedness_with_samples_byThreshold (> 0.6%)","relatedness_value_with_samples_byThreshold (> 0.6%)")
  
  write.table(par_out, "somalier.final.tsv", quote = F, sep="\t")
  
}


args <- commandArgs(trailingOnly = TRUE)
#read in somalier file
somalier_file <- args[1]
sample_id <-args[2]
sample_id <- strsplit(unlist(sample_id), split=',')
sample_id <- unlist(sample_id, use.names = FALSE)
participant_id <- args[3]
participant_id <- strsplit(participant_id, split=',')
participant_id <- unlist(participant_id, use.names = FALSE)


somalier_stats(somalier_file = somalier_file, sample_id = sample_id, participant_id = participant_id)